### ISSUE TITLE
Test failures due to hash randomisation in perl 5.17.6

### ISSUE THREAD

**Issue by andk** [vti/underscore-perl#11]
From perl 5.17.6 upwards tests are failing frequently. Sample fail report:

http://www.cpantesters.org/cpan/report/063347dc-7462-11e3-9aa9-f9970c5d3a7d

Or best illustrated with the matrix:

http://matrix.cpantesters.org/?dist=Underscore%200.04

 v5.17.5-518-g7dc8663 introduced hash key randomization and indeed I could observe changing test results when running the tests often enough. 

You can read more about the change at http://perl5.git.perl.org/perl.git/commit/7dc8663964c66a698d31bbdc8e8abed69bddeec3 or at http://www.perlmonks.org/?node_id=1005122 

HTH && Regards,

(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by andk** [comment]
I just realize that you renamed your module to UnderscoreJS. It has the same problem.

**Comment by vti** [comment]
Fixed in 0.07!
