### ISSUE TITLE
chain doesn't work with sort

### ISSUE THREAD

**Issue by gutschilla** [vti/underscore-perl#6]
I've seen you're added a sort method, but unfortunately, when called in chained context it will always return an array.

``` perl
#This dies with "Can't call method "map" on unblessed reference ":
_([1,2,4,3])->chain->sort->map(sub{$_[0]+1})
```

I my opiniton, it would be better to deprecate/remove the sort method as it's not implemented in Underscore.js either. So removing sort would be "more compatible". I guess the example code on CPAN was a quickshot ;-)

**Comment by chris-l** [comment]
Is not only limited to sort. Using pluck inside a chain also returns an array. Maybe other methods cause problems too, I don't know.

**Comment by chris-l** [comment]
Just adding $self->_finalize( _returned_var_ ) to the returned var on the failing subs seems to fix it.

For instance, on sub pluck: 

``` perl
sub pluck {
   ...
   # return $result;          # It was like this
   $self->_finalize($result); # Now is like this and it works perfect.
}
```

Is there a reason is not like that by default?

**Comment by vti** [comment]
No reason afaik. Just laziness :)

**Comment by chris-l** [comment]
XD I didn't expect that lol.
Well, of course it would be nice if you could fix that. But this is a relief, it means the manual fix I did on my server wasn't something that should not be done for a reason.

**Comment by vti** [comment]
I already started a small cleanup. I hope it won't take too long!

**Comment by richdouglasevans** [comment]
Fixed on my fork: https://github.com/richdouglasevans/underscore-perl

I'm happy to contribute back with a pull request if you like.

**Comment by vti** [comment]
Sure.
