### ISSUE TITLE
CPAN Version out of date

### ISSUE THREAD

**Issue by nonplus** [vti/underscore-perl#9]
CPAN is still on version 0.1.

http://search.cpan.org/~vti/Underscore/

Could you updated it to the latest?

Thanks!

**Comment by vti** [comment]
Should be on its way!

**Comment by Xaerxess** [comment]
Underscore 0.03 is uploaded on CPAN but it's broken (i.e. not indexed correctly by PAUSE, see https://github.com/CPAN-API/metacpan-web/issues/1014).

**Comment by vti** [comment]
I have uploaded new version. Hope it works.

**Comment by vti** [comment]
Hm, again no luck. I guess I better rename it to UnderscoreJS then.

**Comment by vti** [comment]
It seems that it worked.
